<?php

/**
 * 1000 Romanian word pairs for Impostor game
 * Format: [crew_word, impostor_word, category, language]
 * 
 * Critical principles followed:
 * 1. Same Category, Different Objects
 * 2. Avoid Hierarchies & Subsets
 * 3. Balance Similarity
 * 4. Parallel Relationships
 */

return [
    // ============================================
    // FOOD (Mâncare) - 40 pairs
    // ============================================
    ['Pizza', 'Burger', 'Food', 'ro'],
    ['Măr', 'Pară', 'Food', 'ro'],
    ['Pui', 'Curcan', 'Food', 'ro'],
    ['Somon', 'Ton', 'Food', 'ro'],
    ['Cartofi prăjiți', 'Cartofi piure', 'Food', 'ro'],
    ['Spaghete', 'Penne', 'Food', 'ro'],
    ['Brânză', 'Cașcaval', 'Food', 'ro'],
    ['Supă', 'Ciorbă', 'Food', 'ro'],
    ['Pâine', 'Chiflă', 'Food', 'ro'],
    ['Croissant', 'Covrig', 'Food', 'ro'],
    ['Iaurt', 'Brânză de vaci', 'Food', 'ro'],
    ['Miere', 'Sirop', 'Food', 'ro'],
    ['Ciocolată', 'Bomboane', 'Food', 'ro'],
    ['Înghețată', 'Sorbet', 'Food', 'ro'],
    ['Tort', 'Prajitură', 'Food', 'ro'],
    ['Fasole', 'Linte', 'Food', 'ro'],
    ['Orez', 'Quinoa', 'Food', 'ro'],
    ['Porumb', 'Mazăre', 'Food', 'ro'],
    ['Morcov', 'Păstârnac', 'Food', 'ro'],
    ['Roșie', 'Ardei', 'Food', 'ro'],
    ['Castravete', 'Dovlecel', 'Food', 'ro'],
    ['Ceapă', 'Usturoi', 'Food', 'ro'],
    ['Salată verde', 'Spanac', 'Food', 'ro'],
    ['Broccoli', 'Conopidă', 'Food', 'ro'],
    ['Castravete murat', 'Măsline', 'Food', 'ro'],
    ['Cârnați', 'Salam', 'Food', 'ro'],
    ['Șuncă', 'Bacon', 'Food', 'ro'],
    ['Omletă', 'Clătite', 'Food', 'ro'],
    ['Musli', 'Fulgi de ovăz', 'Food', 'ro'],
    ['Lapte', 'Iaurt', 'Food', 'ro'],
    ['Smântână', 'Mascarpone', 'Food', 'ro'],
    ['Unt', 'Margarină', 'Food', 'ro'],
    ['Ulei de măsline', 'Ulei de floarea soarelui', 'Food', 'ro'],
    ['Oțet', 'Lămâie', 'Food', 'ro'],
    ['Muștar', 'Maioneză', 'Food', 'ro'],
    ['Ketchup', 'Sos de roșii', 'Food', 'ro'],
    ['Făină', 'Mălai', 'Food', 'ro'],
    ['Zahăr', 'Miere', 'Food', 'ro'],
    ['Sare', 'Piper', 'Food', 'ro'],
    ['Ceai', 'Cafea', 'Food', 'ro'],
    ['Apă minerală', 'Suc natural', 'Food', 'ro'],

    // ============================================
    // ANIMALS (Animale) - 40 pairs
    // ============================================
    ['Leu', 'Tigru', 'Animals', 'ro'],
    ['Elefant', 'Rinocer', 'Animals', 'ro'],
    ['Girafă', 'Zebra', 'Animals', 'ro'],
    ['Urs', 'Lup', 'Animals', 'ro'],
    ['Vulpe', 'Coiot', 'Animals', 'ro'],
    ['Iepure', 'Veveriță', 'Animals', 'ro'],
    ['Cerb', 'Elan', 'Animals', 'ro'],
    ['Maimuță', 'Lemur', 'Animals', 'ro'],
    ['Gorilă', 'Cimpanzeu', 'Animals', 'ro'],
    ['Cangur', 'Koala', 'Animals', 'ro'],
    ['Crocodil', 'Aligator', 'Animals', 'ro'],
    ['Șarpe', 'Șopârlă', 'Animals', 'ro'],
    ['Broască', 'Salamandră', 'Animals', 'ro'],
    ['Broască țestoasă', 'Broască țestoasă de mare', 'Animals', 'ro'],
    ['Pinguin', 'Albatros', 'Animals', 'ro'],
    ['Vultur', 'Șoim', 'Animals', 'ro'],
    ['Bufniță', 'Ciocănitoare', 'Animals', 'ro'],
    ['Papagal', 'Canar', 'Animals', 'ro'],
    ['Rândunică', 'Rândunică de mare', 'Animals', 'ro'],
    ['Cioară', 'Sturz', 'Animals', 'ro'],
    ['Porumbel', 'Barză', 'Animals', 'ro'],
    ['Flamingo', 'Barză', 'Animals', 'ro'],
    ['Pelican', 'Cocor', 'Animals', 'ro'],
    ['Păun', 'Fazan', 'Animals', 'ro'],
    ['Găină', 'Curcă', 'Animals', 'ro'],
    ['Rață', 'Gâscă', 'Animals', 'ro'],
    ['Câine', 'Lup', 'Animals', 'ro'],
    ['Pisică', 'Jder', 'Animals', 'ro'],
    ['Cal', 'Ponei', 'Animals', 'ro'],
    ['Vacă', 'Bivol', 'Animals', 'ro'],
    ['Oaie', 'Capră', 'Animals', 'ro'],
    ['Porc', 'Mistreț', 'Animals', 'ro'],
    ['Liliac', 'Veveriță zburătoare', 'Animals', 'ro'],
    ['Delfin', 'Balenă', 'Animals', 'ro'],
    ['Rechin', 'Rechin balenă', 'Animals', 'ro'],
    ['Caracatiță', 'Calmar', 'Animals', 'ro'],
    ['Meduză', 'Anemonă de mare', 'Animals', 'ro'],
    ['Furnică', 'Termită', 'Animals', 'ro'],
    ['Fluture', 'Molie', 'Animals', 'ro'],
    ['Albină', 'Bondar', 'Animals', 'ro'],
    ['Țânțar', 'Musca', 'Animals', 'ro'],

    // ============================================
    // NATURE (Natură) - 40 pairs
    // ============================================
    ['Munte', 'Deal', 'Nature', 'ro'],
    ['Pădure', 'Junglă', 'Nature', 'ro'],
    ['Deșert', 'Tundră', 'Nature', 'ro'],
    ['Ocean', 'Mare', 'Nature', 'ro'],
    ['Lac', 'Râu', 'Nature', 'ro'],
    ['Cascadă', 'Izvor', 'Nature', 'ro'],
    ['Vulcan', 'Ghețar', 'Nature', 'ro'],
    ['Stâncă', 'Piatră', 'Nature', 'ro'],
    ['Nisip', 'Pietriș', 'Nature', 'ro'],
    ['Lavă', 'Magmă', 'Nature', 'ro'],
    ['Gheață', 'Zăpadă', 'Nature', 'ro'],
    ['Cețară', 'Burniță', 'Nature', 'ro'],
    ['Furtună', 'Hurican', 'Nature', 'ro'],
    ['Tornadă', 'Vijelie', 'Nature', 'ro'],
    ['Curcubeu', 'Auroră boreală', 'Nature', 'ro'],
    ['Soare', 'Lună', 'Nature', 'ro'],
    ['Stea', 'Planetă', 'Nature', 'ro'],
    ['Cometă', 'Asteroid', 'Nature', 'ro'],
    ['Stejar', 'Brad', 'Nature', 'ro'],
    ['Mesteacăn', 'Plop', 'Nature', 'ro'],
    ['Pin', 'Zadă', 'Nature', 'ro'],
    ['Măceș', 'Mure', 'Nature', 'ro'],
    ['Lămâiță', 'Menta', 'Nature', 'ro'],
    ['Mușchi', 'Licheni', 'Nature', 'ro'],
    ['Ferigă', 'Bambus', 'Nature', 'ro'],
    ['Cactus', 'Agavă', 'Nature', 'ro'],
    ['Orhidee', 'Lalea', 'Nature', 'ro'],
    ['Trandafir', 'Crin', 'Nature', 'ro'],
    ['Floarea soarelui', 'Mac', 'Nature', 'ro'],
    ['Margaretă', 'Narcisă', 'Nature', 'ro'],
    ['Lavandă', 'Iasomie', 'Nature', 'ro'],
    ['Ciocârlie', 'Privighetoare', 'Nature', 'ro'],
    ['Rândunică', 'Codobatură', 'Nature', 'ro'],
    ['Lup de mare', 'Pinguin', 'Nature', 'ro'],
    ['Urs polar', 'Pinguin împărat', 'Nature', 'ro'],
    ['Pădure tropicală', 'Savana', 'Nature', 'ro'],
    ['Prerie', 'Stepă', 'Nature', 'ro'],
    ['Recif de corali', 'Delta', 'Nature', 'ro'],
    ['Peșteră', 'Grota', 'Nature', 'ro'],
    ['Insulă', 'Peninsulă', 'Nature', 'ro'],

    // ============================================
    // OBJECTS (Obiecte) - 40 pairs
    // ============================================
    ['Carte', 'Revistă', 'Objects', 'ro'],
    ['Ziar', 'Jurnal', 'Objects', 'ro'],
    ['Pix', 'Stilou', 'Objects', 'ro'],
    ['Creion', 'Cretă', 'Objects', 'ro'],
    ['Radiou', 'Televizor', 'Objects', 'ro'],
    ['Telefon', 'Tabletă', 'Objects', 'ro'],
    ['Laptop', 'Calculator', 'Objects', 'ro'],
    ['Monitor', 'Televizor', 'Objects', 'ro'],
    ['Tastatură', 'Pian', 'Objects', 'ro'],
    ['Mouse', 'Trackpad', 'Objects', 'ro'],
    ['Imprimantă', 'Copiator', 'Objects', 'ro'],
    ['Lanternă', 'Lampă', 'Objects', 'ro'],
    ['Ceas', 'Cronometru', 'Objects', 'ro'],
    ['Oglindă', 'Sticlă', 'Objects', 'ro'],
    ['Umbrela', 'Baston', 'Objects', 'ro'],
    ['Poșetă', 'Rucsac', 'Objects', 'ro'],
    ['Valiză', 'Geantă', 'Objects', 'ro'],
    ['Portofel', 'Plic', 'Objects', 'ro'],
    ['Cheie', 'Lacăt', 'Objects', 'ro'],
    ['Lanț', 'Coardă', 'Objects', 'ro'],
    ['Șiret', 'Frânghie', 'Objects', 'ro'],
    ['Ac', 'Ață', 'Objects', 'ro'],
    ['Nasture', 'Fermoar', 'Objects', 'ro'],
    ['Benzină', 'Motorină', 'Objects', 'ro'],
    ['Bec', 'Neon', 'Objects', 'ro'],
    ['Baterie', 'Acumulator', 'Objects', 'ro'],
    ['Ștecher', 'Priza', 'Objects', 'ro'],
    ['Cablu', 'Fir', 'Objects', 'ro'],
    ['Panou solar', 'Turbina eoliană', 'Objects', 'ro'],
    ['Recipient', 'Cutie', 'Objects', 'ro'],
    ['Sticlă', 'Borcan', 'Objects', 'ro'],
    ['Pungă', 'Săculeț', 'Objects', 'ro'],
    ['Hârtie', 'Carton', 'Objects', 'ro'],
    ['Plastic', 'Cauciuc', 'Objects', 'ro'],
    ['Lemn', 'Metal', 'Objects', 'ro'],
    ['Aur', 'Argint', 'Objects', 'ro'],
    ['Bronz', 'Cupru', 'Objects', 'ro'],
    ['Diamant', 'Rubin', 'Objects', 'ro'],
    ['Smarald', 'Safir', 'Objects', 'ro'],
    ['Perla', 'Aur', 'Objects', 'ro'],
    ['Ceramică', 'Porțelan', 'Objects', 'ro'],

    // ============================================
    // CLOTHING (Îmbrăcăminte) - 40 pairs
    // ============================================
    ['Cămașă', 'Bluză', 'Clothing', 'ro'],
    ['Tricou', 'Maiou', 'Clothing', 'ro'],
    ['Pulover', 'Cardigan', 'Clothing', 'ro'],
    ['Geacă', 'Palton', 'Clothing', 'ro'],
    ['Haină', 'Trench', 'Clothing', 'ro'],
    ['Sacou', 'Vestă', 'Clothing', 'ro'],
    ['Pantaloni', 'Blugi', 'Clothing', 'ro'],
    ['Pantaloni scurți', 'Fustă', 'Clothing', 'ro'],
    ['Rochie', 'Sarafan', 'Clothing', 'ro'],
    ['Costum de baie', 'Bikini', 'Clothing', 'ro'],
    ['Pijama', 'Halat', 'Clothing', 'ro'],
    ['Șosete', 'Ciorapi', 'Clothing', 'ro'],
    ['Curea', 'Bretele', 'Clothing', 'ro'],
    ['Eșarfă', 'Cravată', 'Clothing', 'ro'],
    ['Fular', 'Batic', 'Clothing', 'ro'],
    ['Pălărie', 'Bască', 'Clothing', 'ro'],
    ['Căciulă', 'Beretă', 'Clothing', 'ro'],
    ['Mănuși', 'Mănuși de piele', 'Clothing', 'ro'],
    ['Papuci', 'Sandale', 'Clothing', 'ro'],
    ['Pantofi', 'Ghete', 'Clothing', 'ro'],
    ['Cizme', 'Cizme de cauciuc', 'Clothing', 'ro'],
    ['Adidași', 'Tenisi', 'Clothing', 'ro'],
    ['Bocanci', 'Ghete', 'Clothing', 'ro'],
    ['Șapcă', 'Pălărie de soare', 'Clothing', 'ro'],
    ['Voal', 'Voaleta', 'Clothing', 'ro'],
    ['Mănușă de lână', 'Mănușă de piele', 'Clothing', 'ro'],
    ['Cămașă de noapte', 'Neglijeu', 'Clothing', 'ro'],
    ['Dres', 'Colanți', 'Clothing', 'ro'],
    ['Chiloți', 'Boxeri', 'Clothing', 'ro'],
    ['Sutien', 'Bustieră', 'Clothing', 'ro'],
    ['Corset', 'Centură', 'Clothing', 'ro'],
    ['Kimono', 'Sari', 'Clothing', 'ro'],
    ['Kilt', 'Fustă lungă', 'Clothing', 'ro'],
    ['Hanorac', 'Bluzon', 'Clothing', 'ro'],
    ['Vestă de salvare', 'Geacă de schi', 'Clothing', 'ro'],
    ['Combinezon', 'Salopetă', 'Clothing', 'ro'],
    ['Halat de baie', 'Prosop', 'Clothing', 'ro'],
    ['Șorț', 'Sort de bucătărie', 'Clothing', 'ro'],
    ['Mănușă de bucătărie', 'Mănușă de grădină', 'Clothing', 'ro'],
    ['Botine', 'Pantofi cu toc', 'Clothing', 'ro'],

    // ============================================
    // SPORTS (Sport) - 40 pairs
    // ============================================
    ['Fotbal', 'Rugby', 'Sports', 'ro'],
    ['Baschet', 'Volei', 'Sports', 'ro'],
    ['Tenis', 'Badminton', 'Sports', 'ro'],
    ['Tenis de masă', 'Squash', 'Sports', 'ro'],
    ['Golf', 'Croquet', 'Sports', 'ro'],
    ['Hochei', 'Polo pe apă', 'Sports', 'ro'],
    ['Cricket', 'Baseball', 'Sports', 'ro'],
    ['Box', 'Kickboxing', 'Sports', 'ro'],
    ['Judo', 'Karate', 'Sports', 'ro'],
    ['Aikido', 'Taekwondo', 'Sports', 'ro'],
    ['Lupte', 'Sumo', 'Sports', 'ro'],
    ['Înot', 'Scufundări', 'Sports', 'ro'],
    ['Surf', 'Windsurfing', 'Sports', 'ro'],
    ['Kitesurfing', 'Wakeboarding', 'Sports', 'ro'],
    ['Schi', 'Snowboard', 'Sports', 'ro'],
    ['Patinaj', 'Hochei pe gheață', 'Sports', 'ro'],
    ['Gimnastică', 'Aerobic', 'Sports', 'ro'],
    ['Yoga', 'Pilates', 'Sports', 'ro'],
    ['Atletism', 'Maraton', 'Sports', 'ro'],
    ['Sărituri', 'Aruncarea suliței', 'Sports', 'ro'],
    ['Ciclism', 'Mountain bike', 'Sports', 'ro'],
    ['BMX', 'Ciclism rutier', 'Sports', 'ro'],
    ['Raliu', 'Formula 1', 'Sports', 'ro'],
    ['MotoGP', 'Motocros', 'Sports', 'ro'],
    ['Călărie', 'Polo', 'Sports', 'ro'],
    ['Tir cu arcul', 'Săgeți', 'Sports', 'ro'],
    ['Schiț', 'Biatlon', 'Sports', 'ro'],
    ['Triatlon', 'Pentatlon', 'Sports', 'ro'],
    ['Escaladă', 'Alpinism', 'Sports', 'ro'],
    ['Parapantă', 'Parașutism', 'Sports', 'ro'],
    ['Bungee jumping', 'Tiroliană', 'Sports', 'ro'],
    ['Parkour', 'Freerun', 'Sports', 'ro'],
    ['Skateboard', 'Longboard', 'Sports', 'ro'],
    ['Roller', 'Patinaj cu rotile', 'Sports', 'ro'],
    ['Dans sportiv', 'Gimnastică ritmică', 'Sports', 'ro'],
    ['Șah', 'Dame', 'Sports', 'ro'],
    ['Biliard', 'Snooker', 'Sports', 'ro'],
    ['Darts', 'Popice', 'Sports', 'ro'],
    ['Pescuit', 'Vânătoare', 'Sports', 'ro'],
    ['Escrimă', 'Kendo', 'Sports', 'ro'],

    // ============================================
    // PROFESSIONS (Profesii) - 40 pairs
    // ============================================
    ['Doctor', 'Chirurg', 'Professions', 'ro'],
    ['Asistentă', 'Infirmieră', 'Professions', 'ro'],
    ['Farmacist', 'Veterinar', 'Professions', 'ro'],
    ['Dentist', 'Ortodont', 'Professions', 'ro'],
    ['Profesor', 'Lector', 'Professions', 'ro'],
    ['Învățător', 'Educatoare', 'Professions', 'ro'],
    ['Inginer', 'Arhitect', 'Professions', 'ro'],
    ['Constructor', 'Măcelar', 'Professions', 'ro'],
    ['Electrician', 'Instalator', 'Professions', 'ro'],
    ['Tâmplar', 'Dulgher', 'Professions', 'ro'],
    ['Zugrav', 'Tencuitor', 'Professions', 'ro'],
    ['Bucătar', 'Cofetar', 'Professions', 'ro'],
    ['Barman', 'Chelner', 'Professions', 'ro'],
    ['Recepționer', 'Concierge', 'Professions', 'ro'],
    ['Pilot', 'Copilot', 'Professions', 'ro'],
    ['Șofer', 'Taximetrist', 'Professions', 'ro'],
    ['Polițist', 'Detectiv', 'Professions', 'ro'],
    ['Pompier', 'Jandarm', 'Professions', 'ro'],
    ['Soldat', 'Ofițer', 'Professions', 'ro'],
    ['Judecător', 'Avocat', 'Professions', 'ro'],
    ['Procuror', 'Notar', 'Professions', 'ro'],
    ['Contabil', 'Economist', 'Professions', 'ro'],
    ['Bancher', 'Agent de asigurări', 'Professions', 'ro'],
    ['Manager', 'Director', 'Professions', 'ro'],
    ['Secretară', 'Asistent personal', 'Professions', 'ro'],
    ['Programator', 'Dezvoltator web', 'Professions', 'ro'],
    ['Designer', 'Grafician', 'Professions', 'ro'],
    ['Fotograf', 'Cameraman', 'Professions', 'ro'],
    ['Jurnalist', 'Redactor', 'Professions', 'ro'],
    ['Prezentator', 'Actor', 'Professions', 'ro'],
    ['Regizor', 'Producător', 'Professions', 'ro'],
    ['Muzician', 'Compozitor', 'Professions', 'ro'],
    ['Pictor', 'Sculptor', 'Professions', 'ro'],
    ['Scriitor', 'Poet', 'Professions', 'ro'],
    ['Bibliotecar', 'Arhivar', 'Professions', 'ro'],
    ['Antrenor', 'Arbitru', 'Professions', 'ro'],
    ['Psiholog', 'Psihiatru', 'Professions', 'ro'],
    ['Nutriționist', 'Kinetoterapeut', 'Professions', 'ro'],
    ['Cosmeticiană', 'Frizer', 'Professions', 'ro'],
    ['Mecanic', 'Vulcanizator', 'Professions', 'ro'],

    // ============================================
    // PLACES (Locuri) - 40 pairs
    // ============================================
    ['Restaurant', 'Cafenea', 'Places', 'ro'],
    ['Bar', 'Club', 'Places', 'ro'],
    ['Hotel', 'Motel', 'Places', 'ro'],
    ['Spital', 'Clinică', 'Places', 'ro'],
    ['Farmacie', 'Drogherie', 'Places', 'ro'],
    ['Școală', 'Grădiniță', 'Places', 'ro'],
    ['Universitate', 'Colegiu', 'Places', 'ro'],
    ['Bibliotecă', 'Librărie', 'Places', 'ro'],
    ['Muzeu', 'Galerie de artă', 'Places', 'ro'],
    ['Teatru', 'Operă', 'Places', 'ro'],
    ['Cinematograf', 'Teatru de vară', 'Places', 'ro'],
    ['Stadion', 'Sala de sport', 'Places', 'ro'],
    ['Parc', 'Grădină botanică', 'Places', 'ro'],
    ['Zoo', 'Acvariu', 'Places', 'ro'],
    ['Mall', 'Centru comercial', 'Places', 'ro'],
    ['Magazin', 'Butic', 'Places', 'ro'],
    ['Supermarket', 'Hipermarket', 'Places', 'ro'],
    ['Piață', 'Târg', 'Places', 'ro'],
    ['Biserică', 'Catedrală', 'Places', 'ro'],
    ['Mănăstire', 'Schit', 'Places', 'ro'],
    ['Cimitir', 'Columbar', 'Places', 'ro'],
    ['Gară', 'Autogară', 'Places', 'ro'],
    ['Aeroport', 'Port', 'Places', 'ro'],
    ['Benzinărie', 'Service auto', 'Places', 'ro'],
    ['Bancă', 'Casa de schimb', 'Places', 'ro'],
    ['Poștă', 'Curierat', 'Places', 'ro'],
    ['Primărie', 'Consiliu județean', 'Places', 'ro'],
    ['Tribunal', 'Judecătorie', 'Places', 'ro'],
    ['Poliție', 'Jandarmerie', 'Places', 'ro'],
    ['Penitenciar', 'Arest', 'Places', 'ro'],
    ['Salon de înfrumusețare', 'Spa', 'Places', 'ro'],
    ['Sală de fitness', 'Piscină', 'Places', 'ro'],
    ['Saună', 'Hammam', 'Places', 'ro'],
    ['Cabinet medical', 'Laborator analize', 'Places', 'ro'],
    ['Dentist', 'Ortodont', 'Places', 'ro'],
    ['Veterinar', 'Pensiune animale', 'Places', 'ro'],
    ['Service telefoane', 'Magazin electronice', 'Places', 'ro'],
    ['Frizerie', 'Coafor', 'Places', 'ro'],
    ['Spălătorie', 'Curățătorie chimică', 'Places', 'ro'],
    ['Service calculatoare', 'Magazin IT', 'Places', 'ro'],

    // ============================================
    // BODY (Corp) - 40 pairs
    // ============================================
    ['Cap', 'Față', 'Body', 'ro'],
    ['Frunte', 'Obraz', 'Body', 'ro'],
    ['Ochi', 'Ureche', 'Body', 'ro'],
    ['Nas', 'Gură', 'Body', 'ro'],
    ['Buze', 'Limba', 'Body', 'ro'],
    ['Dinte', 'Măsea', 'Body', 'ro'],
    ['Bărbie', 'Gât', 'Body', 'ro'],
    ['Umăr', 'Cot', 'Body', 'ro'],
    ['Braț', 'Antebraț', 'Body', 'ro'],
    ['Mână', 'Deget', 'Body', 'ro'],
    ['Palma', 'Dosul mâinii', 'Body', 'ro'],
    ['Piept', 'Coaste', 'Body', 'ro'],
    ['Spate', 'Șale', 'Body', 'ro'],
    ['Buric', 'Abdomen', 'Body', 'ro'],
    ['Coapsă', 'Genunchi', 'Body', 'ro'],
    ['Picior', 'Labă picior', 'Body', 'ro'],
    ['Călcâi', 'Deget de la picior', 'Body', 'ro'],
    ['Inimă', 'Plămân', 'Body', 'ro'],
    ['Ficat', 'Rinichi', 'Body', 'ro'],
    ['Stomac', 'Intestin', 'Body', 'ro'],
    ['Creier', 'Măduva spinării', 'Body', 'ro'],
    ['Os', 'Cartilaj', 'Body', 'ro'],
    ['Mușchi', 'Tendon', 'Body', 'ro'],
    ['Pielea', 'Unghie', 'Body', 'ro'],
    ['Păr', 'Barbă', 'Body', 'ro'],
    ['Sprânceană', 'Gene', 'Body', 'ro'],
    ['Sânge', 'Limfa', 'Body', 'ro'],
    ['Vână', 'Arteră', 'Body', 'ro'],
    ['Nerv', 'Neuron', 'Body', 'ro'],
    ['Celulă', 'Bacterie', 'Body', 'ro'],
    ['Virus', 'Microb', 'Body', 'ro'],
    ['Sân', 'Mamelon', 'Body', 'ro'],
    ['Călcâi', 'Fleză', 'Body', 'ro'],
    ['Palmă', 'Pumn', 'Body', 'ro'],
    ['Deget mare', 'Deget mic', 'Body', 'ro'],
    ['Talpă', 'Tălpiță', 'Body', 'ro'],
    ['Vânătaie', 'Cicatrice', 'Body', 'ro'],
    ['Pistrui', 'Aluniță', 'Body', 'ro'],
    ['Rid', 'Coș', 'Body', 'ro'],
    ['Transpirație', 'Salivă', 'Body', 'ro'],

    // ============================================
    // COLORS (Culori) - 40 pairs
    // ============================================
    ['Roșu', 'Portocaliu', 'Colors', 'ro'],
    ['Galben', 'Verde', 'Colors', 'ro'],
    ['Albastru', 'Indigo', 'Colors', 'ro'],
    ['Violet', 'Mov', 'Colors', 'ro'],
    ['Roz', 'Magenta', 'Colors', 'ro'],
    ['Maro', 'Bej', 'Colors', 'ro'],
    ['Negru', 'Gri', 'Colors', 'ro'],
    ['Alb', 'Crem', 'Colors', 'ro'],
    ['Argintiu', 'Auriu', 'Colors', 'ro'],
    ['Bronz', 'Cupru', 'Colors', 'ro'],
    ['Roșu aprins', 'Roșu închis', 'Colors', 'ro'],
    ['Verde deschis', 'Verde închis', 'Colors', 'ro'],
    ['Albastru deschis', 'Albastru închis', 'Colors', 'ro'],
    ['Turcoaz', 'Cyan', 'Colors', 'ro'],
    ['Lila', 'Lavandă', 'Colors', 'ro'],
    ['Coral', 'Piersică', 'Colors', 'ro'],
    ['Salmon', 'Somn', 'Colors', 'ro'],
    ['Kaki', 'Măsliniu', 'Colors', 'ro'],
    ['Turcoaz', 'Azuriu', 'Colors', 'ro'],
    ['Bordo', 'Visiniu', 'Colors', 'ro'],
    ['Cărămiziu', 'Teracotă', 'Colors', 'ro'],
    ['Ocher', 'Mustar', 'Colors', 'ro'],
    ['Ciocolatiu', 'Cafeniu', 'Colors', 'ro'],
    ['Grafen', 'Antracit', 'Colors', 'ro'],
    ['Perlat', 'Metalizat', 'Colors', 'ro'],
    ['Transparent', 'Translucid', 'Colors', 'ro'],
    ['Mat', 'Lucios', 'Colors', 'ro'],
    ['Neon', 'Fluorescent', 'Colors', 'ro'],
    ['Pastel', 'Saturat', 'Colors', 'ro'],
    ['Cald', 'Rece', 'Colors', 'ro'],
    ['Roșu sângeriu', 'Roșu bordo', 'Colors', 'ro'],
    ['Verde crud', 'Verde smarald', 'Colors', 'ro'],
    ['Albastru cobalt', 'Albastru marin', 'Colors', 'ro'],
    ['Violet mov', 'Violet prună', 'Colors', 'ro'],
    ['Galben lămâie', 'Galben muștar', 'Colors', 'ro'],
    ['Portocaliu mandarin', 'Portocaliu dovleac', 'Colors', 'ro'],
    ['Roz pudră', 'Roz fuchsia', 'Colors', 'ro'],
    ['Gri deschis', 'Gri închis', 'Colors', 'ro'],
    ['Negru lucios', 'Negru mat', 'Colors', 'ro'],
    ['Alb perlat', 'Alb spumă', 'Colors', 'ro'],

    // ============================================
    // VEHICLES (Vehicule) - 40 pairs
    // ============================================
    ['Mașină', 'Autobuz', 'Vehicles', 'ro'],
    ['Troleibuz', 'Tramvai', 'Vehicles', 'ro'],
    ['Metrou', 'Tren', 'Vehicles', 'ro'],
    ['Avion', 'Elicopter', 'Vehicles', 'ro'],
    ['Navă', 'Submarin', 'Vehicles', 'ro'],
    ['Barcă', 'Yacht', 'Vehicles', 'ro'],
    ['Canoe', 'Caiac', 'Vehicles', 'ro'],
    ['Bicicletă', 'Motocicletă', 'Vehicles', 'ro'],
    ['Scuter', 'Moped', 'Vehicles', 'ro'],
    ['Tractor', 'Combinezon', 'Vehicles', 'ro'],
    ['Camion', 'TIR', 'Vehicles', 'ro'],
    ['Furgonetă', 'Duba', 'Vehicles', 'ro'],
    ['Ambulanță', 'Pompieri', 'Vehicles', 'ro'],
    ['Poliție', 'Taxi', 'Vehicles', 'ro'],
    ['Raliu', 'Formula 1', 'Vehicles', 'ro'],
    ['MotoGP', 'Motocros', 'Vehicles', 'ro'],
    ['Autocar', 'Microbuz', 'Vehicles', 'ro'],
    ['Rachetă', 'Navetă spațială', 'Vehicles', 'ro'],
    ['Satelit', 'Stație spațială', 'Vehicles', 'ro'],
    ['Lună rover', 'Mars rover', 'Vehicles', 'ro'],
    ['Balon', 'Dirijabil', 'Vehicles', 'ro'],
    ['Parașută', 'Deltaplan', 'Vehicles', 'ro'],
    ['Tanc', 'Transportor', 'Vehicles', 'ro'],
    ['Jeep', 'Hummer', 'Vehicles', 'ro'],
    ['Cabriolet', 'Roadster', 'Vehicles', 'ro'],
    ['Sedan', 'Break', 'Vehicles', 'ro'],
    ['Hatchback', 'Coupé', 'Vehicles', 'ro'],
    ['SUV', 'Crossover', 'Vehicles', 'ro'],
    ['Monovolum', 'Minivan', 'Vehicles', 'ro'],
    ['Pickup', 'Camionetă', 'Vehicles', 'ro'],
    ['Limuzină', 'Berlină', 'Vehicles', 'ro'],
    ['Targa', 'Spyder', 'Vehicles', 'ro'],
    ['Hot rod', 'Muscle car', 'Vehicles', 'ro'],
    ['Autoturism electric', 'Hybrid', 'Vehicles', 'ro'],
    ['Hoverboard', 'Segway', 'Vehicles', 'ro'],
    ['Trotinetă', 'Skateboard electric', 'Vehicles', 'ro'],
    ['Bicicletă electrică', 'Triciclu', 'Vehicles', 'ro'],
    ['Șlep', 'Remorcă', 'Vehicles', 'ro'],
    ['Autogreder', 'Buldoexcavator', 'Vehicles', 'ro'],
    ['Macara', 'Turn de ridicare', 'Vehicles', 'ro'],

    // ============================================
    // MUSIC (Muzică) - 40 pairs
    // ============================================
    ['Chitară', 'Vioară', 'Music', 'ro'],
    ['Pian', 'Orga', 'Music', 'ro'],
    ['Tobe', 'Xilofon', 'Music', 'ro'],
    ['Flaut', 'Clarinet', 'Music', 'ro'],
    ['Saxofon', 'Trompetă', 'Music', 'ro'],
    ['Trombon', 'Tubă', 'Music', 'ro'],
    ['Violoncel', 'Contrabas', 'Music', 'ro'],
    ['Acordeon', 'Concertina', 'Music', 'ro'],
    ['Mandolină', 'Balalaică', 'Music', 'ro'],
    ['Banjo', 'Ukulele', 'Music', 'ro'],
    ['Harpă', 'Liră', 'Music', 'ro'],
    ['Tamburină', 'Triunghi', 'Music', 'ro'],
    ['Clape', 'Sintetizator', 'Music', 'ro'],
    ['Baterie electronică', 'Pad-uri', 'Music', 'ro'],
    ['Microfon', 'Amplificator', 'Music', 'ro'],
    ['Căști', 'Boxe', 'Music', 'ro'],
    ['Mixer', 'Platoane', 'Music', 'ro'],
    ['Rock', 'Pop', 'Music', 'ro'],
    ['Jazz', 'Blues', 'Music', 'ro'],
    ['Clasică', 'Baroc', 'Music', 'ro'],
    ['Operă', 'Operetă', 'Music', 'ro'],
    ['Rap', 'Hip-hop', 'Music', 'ro'],
    ['R&B', 'Soul', 'Music', 'ro'],
    ['Funk', 'Disco', 'Music', 'ro'],
    ['Reggae', 'Ska', 'Music', 'ro'],
    ['Country', 'Folk', 'Music', 'ro'],
    ['Electronică', 'House', 'Music', 'ro'],
    ['Techno', 'Trance', 'Music', 'ro'],
    ['Dubstep', 'Drum and bass', 'Music', 'ro'],
    ['Metal', 'Punk', 'Music', 'ro'],
    ['Indie', 'Alternative', 'Music', 'ro'],
    ['Ambient', 'New age', 'Music', 'ro'],
    ['Latină', 'Flamenco', 'Music', 'ro'],
    ['Muzică clasică indiană', 'Gamelan', 'Music', 'ro'],
    ['Muzică africană', 'Muzică braziliană', 'Music', 'ro'],
    ['Cântăreț', 'Compozitor', 'Music', 'ro'],
    ['DJ', 'Producător', 'Music', 'ro'],
    ['Orchestră', 'Cor', 'Music', 'ro'],
    ['Recital', 'Concert', 'Music', 'ro'],
    ['Simfonie', 'Concerto', 'Music', 'ro'],

    // ============================================
    // SCIENCE (Știință) - 40 pairs
    // ============================================
    ['Fizică', 'Chimie', 'Science', 'ro'],
    ['Biologie', 'Botanică', 'Science', 'ro'],
    ['Zoologie', 'Anatomie', 'Science', 'ro'],
    ['Astronomie', 'Astrofizică', 'Science', 'ro'],
    ['Geologie', 'Geografie', 'Science', 'ro'],
    ['Meteorologie', 'Climatologie', 'Science', 'ro'],
    ['Oceanografie', 'Limnologie', 'Science', 'ro'],
    ['Ecologie', 'Mediu', 'Science', 'ro'],
    ['Genetică', 'Biotehnologie', 'Science', 'ro'],
    ['Microbiologie', 'Virologie', 'Science', 'ro'],
    ['Paleontologie', 'Arheologie', 'Science', 'ro'],
    ['Antropologie', 'Sociologie', 'Science', 'ro'],
    ['Psihologie', 'Neuroștiință', 'Science', 'ro'],
    ['Lingvistică', 'Filologie', 'Science', 'ro'],
    ['Filosofie', 'Logică', 'Science', 'ro'],
    ['Matematică', 'Statistică', 'Science', 'ro'],
    ['Algebră', 'Geometrie', 'Science', 'ro'],
    ['Trigonometrie', 'Calculus', 'Science', 'ro'],
    ['Teoria numerelor', 'Teoria grafurilor', 'Science', 'ro'],
    ['Informatică', 'Inteligență artificială', 'Science', 'ro'],
    ['Robotica', 'Cibernetica', 'Science', 'ro'],
    ['Energie nucleară', 'Energie solară', 'Science', 'ro'],
    ['Fuziune', 'Fisiune', 'Science', 'ro'],
    ['Teoria relativității', 'Mecanica cuantică', 'Science', 'ro'],
    ['Big Bang', 'Teoria șirurilor', 'Science', 'ro'],
    ['Gaură neagră', 'Gaură de vierme', 'Science', 'ro'],
    ['Materie întunecată', 'Energie întunecată', 'Science', 'ro'],
    ['ADN', 'ARN', 'Science', 'ro'],
    ['Celulă', 'Organelă', 'Science', 'ro'],
    ['Atom', 'Moleculă', 'Science', 'ro'],
    ['Electron', 'Proton', 'Science', 'ro'],
    ['Neutron', 'Foton', 'Science', 'ro'],
    ['Quarc', 'Lepton', 'Science', 'ro'],
    ['Boson', 'Fermion', 'Science', 'ro'],
    ['Antimaterie', 'Materie', 'Science', 'ro'],
    ['Laser', 'Maser', 'Science', 'ro'],
    ['Telescop', 'Microscop', 'Science', 'ro'],
    ['Laborator', 'Observator', 'Science', 'ro'],
    ['Experiment', 'Observație', 'Science', 'ro'],
    ['Teoremă', 'Hipoteză', 'Science', 'ro'],

    // ============================================
    // HISTORY (Istorie) - 40 pairs
    // ============================================
    ['Război', 'Bătălie', 'History', 'ro'],
    ['Imperiu', 'Regat', 'History', 'ro'],
    ['Monarhie', 'Republică', 'History', 'ro'],
    ['Dictatură', 'Democrație', 'History', 'ro'],
    ['Revoluție', 'Rebeliune', 'History', 'ro'],
    ['Invazie', 'Asediu', 'History', 'ro'],
    ['Tratat', 'Alianță', 'History', 'ro'],
    ['Colonizare', 'Imperialism', 'History', 'ro'],
    ['Sclavie', 'Feudalism', 'History', 'ro'],
    ['Cruciade', 'Jihad', 'History', 'ro'],
    ['Renaștere', 'Iluminism', 'History', 'ro'],
    ['Reforma', 'Contrareforma', 'History', 'ro'],
    ['Revoluție industrială', 'Revoluție agricolă', 'History', 'ro'],
    ['Epoca de piatră', 'Epoca de bronz', 'History', 'ro'],
    ['Epoca fierului', 'Evul mediu', 'History', 'ro'],
    ['Imperiul Roman', 'Imperiul Bizantin', 'History', 'ro'],
    ['Imperiul Otoman', 'Imperiul Mongol', 'History', 'ro'],
    ['Imperiul Britanic', 'Imperiul Francez', 'History', 'ro'],
    ['Al doilea război mondial', 'Primul război mondial', 'History', 'ro'],
    ['Război rece', 'Războiul din Vietnam', 'History', 'ro'],
    ['Revoluția Franceză', 'Revoluția Americană', 'History', 'ro'],
    ['Revoluția Rusă', 'Revoluția Chineză', 'History', 'ro'],
    ['Căderea Zidului Berlinului', 'Reunificarea Germaniei', 'History', 'ro'],
    ['Dezmembrarea URSS', 'Primăvara de la Praga', 'History', 'ro'],
    ['Marea Criză Economică', 'Criza petrolului', 'History', 'ro'],
    ['Proclamarea independenței SUA', 'Declarația drepturilor omului', 'History', 'ro'],
    ['Tratatul de la Versailles', 'Tratatul de la Trianon', 'History', 'ro'],
    ['Conferința de la Yalta', 'Conferința de la Potsdam', 'History', 'ro'],
    ['Uniunea Europeană', 'NATO', 'History', 'ro'],
    ['Națiunile Unite', 'Liga Națiunilor', 'History', 'ro'],
    ['Faraon', 'Împărat', 'History', 'ro'],
    ['Rege', 'Regină', 'History', 'ro'],
    ['Prinț', 'Duce', 'History', 'ro'],
    ['Președinte', 'Prim-ministru', 'History', 'ro'],
    ['General', 'Amiral', 'History', 'ro'],
    ['Explorator', 'Conchistador', 'History', 'ro'],
    ['Cruciat', 'Samurai', 'History', 'ro'],
    ['Viking', 'Cavaler', 'History', 'ro'],
    ['Gladiator', 'Legionar', 'History', 'ro'],
    ['Fosilă', 'Artifact', 'History', 'ro'],

    // ============================================
    // TOOLS (Unelte) - 40 pairs
    // ============================================
    ['Ciocan', 'Clește', 'Tools', 'ro'],
    ['Șurubelniță', 'Cheie', 'Tools', 'ro'],
    ['Fierăstrău', 'Daltă', 'Tools', 'ro'],
    ['Bormașină', 'Polizor', 'Tools', 'ro'],
    [' patent', 'Șurub', 'Tools', 'ro'],
    ['Piton', 'Cârlig', 'Tools', 'ro'],
    ['Lanț', 'Frânghie', 'Tools', 'ro'],
    ['Level', 'Ruletă', 'Tools', 'ro'],
    ['Compas', 'Raportor', 'Tools', 'ro'],
    ['Echer', 'Linie', 'Tools', 'ro'],
    ['Aspirator', 'Mop', 'Tools', 'ro'],
    ['Mătura', 'Faras', 'Tools', 'ro'],
    ['Spălător de geamuri', 'Racletă', 'Tools', 'ro'],
    ['Fier de călcat', 'Statie de călcat', 'Tools', 'ro'],
    ['Mașină de spălat', 'Uscător', 'Tools', 'ro'],
    ['Frigider', 'Congelator', 'Tools', 'ro'],
    ['Cuptor', 'Cuptor cu microunde', 'Tools', 'ro'],
    ['Aragaz', 'Plită', 'Tools', 'ro'],
    ['Mixer', 'Blender', 'Tools', 'ro'],
    ['Robot de bucătărie', 'Tocător', 'Tools', 'ro'],
    ['Râșniță', 'Storcător', 'Tools', 'ro'],
    ['Cafetieră', 'Espressor', 'Tools', 'ro'],
    ['Fierbător', 'Ibric', 'Tools', 'ro'],
    ['Grătar', 'Tigaie', 'Tools', 'ro'],
    ['Crată', 'Oală sub presiune', 'Tools', 'ro'],
    ['Tavă', 'Vas de copt', 'Tools', 'ro'],
    ['Storcător de usturoi', 'Razătoare', 'Tools', 'ro'],
    ['Cuțit de bucătărie', 'Foarfecă de bucătărie', 'Tools', 'ro'],
    ['Tocător', 'Platou', 'Tools', 'ro'],
    ['Desfăcător', 'Tirbușon', 'Tools', 'ro'],
    ['Dozator', 'Sticlă', 'Tools', 'ro'],
    ['Prosop de hârtie', 'Șervețel', 'Tools', 'ro'],
    ['Folie de aluminiu', 'Folie de plastic', 'Tools', 'ro'],
    ['Pungă de gunoi', 'Coș de gunoi', 'Tools', 'ro'],
    ['Mănușă de bucătărie', 'Șorț', 'Tools', 'ro'],
    ['Ventilator', 'Aer condiționat', 'Tools', 'ro'],
    ['Calorifer', 'Termostat', 'Tools', 'ro'],
    ['Umidificator', 'Dezumidificator', 'Tools', 'ro'],
    ['Purificator de aer', 'Ionizator', 'Tools', 'ro'],
    ['Aspirator robot', 'Mop electric', 'Tools', 'ro'],

    // ============================================
    // FURNITURE (Mobilă) - 40 pairs
    // ============================================
    ['Canapea', 'Fotoliu', 'Furniture', 'ro'],
    ['Pat', 'Saltea', 'Furniture', 'ro'],
    ['Masă', 'Birou', 'Furniture', 'ro'],
    ['Scaun', 'Taburet', 'Furniture', 'ro'],
    ['Dulap', 'Sertar', 'Furniture', 'ro'],
    ['Comodă', 'Noptieră', 'Furniture', 'ro'],
    ['Raft', 'Bibliotecă', 'Furniture', 'ro'],
    ['Vitrină', 'Bufet', 'Furniture', 'ro'],
    ['Măsuță de cafea', 'Măsuță laterală', 'Furniture', 'ro'],
    ['Măsuță de toaletă', 'Consolă', 'Furniture', 'ro'],
    ['Puf', 'Banchetă', 'Furniture', 'ro'],
    ['Pat supraetajat', 'Pat canapea', 'Furniture', 'ro'],
    ['Șifonier', 'Umeraș', 'Furniture', 'ro'],
    ['Oglindă', 'Oglindă de masă', 'Furniture', 'ro'],
    ['Candelabru', 'Lampă de masă', 'Furniture', 'ro'],
    ['Veioză', 'Lampadar', 'Furniture', 'ro'],
    ['Covoare', 'Mochetă', 'Furniture', 'ro'],
    ['Perdea', 'Draperie', 'Furniture', 'ro'],
    ['Jaluzea', 'Rulou', 'Furniture', 'ro'],
    ['Plasă de țânțari', 'Perdea de ușă', 'Furniture', 'ro'],
    ['Cuier', 'Pantofar', 'Furniture', 'ro'],
    ['Suport de umbrele', 'Coș de rufe', 'Furniture', 'ro'],
    ['Masă de călcat', 'Suport de haine', 'Furniture', 'ro'],
    ['Suport de reviste', 'Suport de sticle', 'Furniture', 'ro'],
    ['Vază', 'Ghiveci', 'Furniture', 'ro'],
    ['Tablou', 'Oglindă decorativă', 'Furniture', 'ro'],
    ['Ceas de perete', 'Statuetă', 'Furniture', 'ro'],
    ['Lumânare', 'Lămpiță', 'Furniture', 'ro'],
    ['Pernă', 'Pătură', 'Furniture', 'ro'],
    ['Plapumă', 'Cuvertură', 'Furniture', 'ro'],
    ['Cearceaf', 'Față de pernă', 'Furniture', 'ro'],
    ['Cuvertură de pat', 'Pilotă', 'Furniture', 'ro'],
    ['Covoare', 'Preș', 'Furniture', 'ro'],
    ['Mocheta', 'Parchet', 'Furniture', 'ro'],
    ['Gresie', 'Faianță', 'Furniture', 'ro'],
    ['Tapet', 'Vopsea lavabilă', 'Furniture', 'ro'],
    ['Grilaj', 'Balustradă', 'Furniture', 'ro'],
    ['Ușă', 'Fereastră', 'Furniture', 'ro'],
    ['Roletă', 'Plasă de insecte', 'Furniture', 'ro'],
    ['Măsuță de grădină', 'Șezlong', 'Furniture', 'ro'],

    // ============================================
    // TIME (Timp) - 40 pairs
    // ============================================
    ['Secundă', 'Minut', 'Time', 'ro'],
    ['Oră', 'Zi', 'Time', 'ro'],
    ['Săptămână', 'Lună', 'Time', 'ro'],
    ['An', 'Deceniu', 'Time', 'ro'],
    ['Secol', 'Mileniul', 'Time', 'ro'],
    ['Eon', 'Eră', 'Time', 'ro'],
    ['Dimineață', 'Amiază', 'Time', 'ro'],
    ['După-amiază', 'Seară', 'Time', 'ro'],
    ['Noapte', 'Răsărit', 'Time', 'ro'],
    ['Apus', 'Amurg', 'Time', 'ro'],
    ['Răsărit de soare', 'Răsărit de lună', 'Time', 'ro'],
    ['Ziua', 'Noaptea', 'Time', 'ro'],
    ['Zori', 'Amurg', 'Time', 'ro'],
    ['Miezul nopții', 'Miezul zilei', 'Time', 'ro'],
    ['Oră de vară', 'Oră de iarnă', 'Time', 'ro'],
    ['Fus orar', 'Meridian', 'Time', 'ro'],
    ['Cronometru', 'Temporizator', 'Time', 'ro'],
    ['Ceas cu pendul', 'Ceas digital', 'Time', 'ro'],
    ['Ceas de mână', 'Ceas de perete', 'Time', 'ro'],
    ['Calendar', 'Agendă', 'Time', 'ro'],
    ['Program', 'Orar', 'Time', 'ro'],
    ['Termen limită', 'Data scadenței', 'Time', 'ro'],
    ['Perioadă', 'Interval', 'Time', 'ro'],
    ['Durată', 'Termen', 'Time', 'ro'],
    ['Istoric', 'Trecut', 'Time', 'ro'],
    ['Prezent', 'Moment', 'Time', 'ro'],
    ['Viitor', 'Perspectivă', 'Time', 'ro'],
    ['Previziune', 'Prognostic', 'Time', 'ro'],
    ['Amintire', 'Rememorare', 'Time', 'ro'],
    ['Nostalgie', 'Melancolie', 'Time', 'ro'],
    ['Așteptare', 'Răbdare', 'Time', 'ro'],
    ['Urgent', 'Prioritar', 'Time', 'ro'],
    ['Imediat', 'Instantaneu', 'Time', 'ro'],
    ['Curând', 'În curând', 'Time', 'ro'],
    ['Târziu', 'Întârziat', 'Time', 'ro'],
    ['Devreme', 'Prematur', 'Time', 'ro'],
    ['La timp', 'Punctual', 'Time', 'ro'],
    ['Periodic', 'Regulat', 'Time', 'ro'],
    ['Continuu', 'Constant', 'Time', 'ro'],
    ['Temporar', 'Provizoriu', 'Time', 'ro'],

    // ============================================
    // EMOTIONS (Emoții) - 40 pairs
    // ============================================
    ['Fericire', 'Bucurie', 'Emotions', 'ro'],
    ['Tristețe', 'Melancolie', 'Emotions', 'ro'],
    ['Furie', 'Mânie', 'Emotions', 'ro'],
    ['Frustrare', 'Iritare', 'Emotions', 'ro'],
    ['Teama', 'Anxietate', 'Emotions', 'ro'],
    ['Panică', 'Fobie', 'Emotions', 'ro'],
    ['Surpriză', 'Uimire', 'Emotions', 'ro'],
    ['Șoc', 'Consternare', 'Emotions', 'ro'],
    ['Dragoste', 'Afecțiune', 'Emotions', 'ro'],
    ['Pasiune', 'Obsesie', 'Emotions', 'ro'],
    ['Invidie', 'Gelozie', 'Emotions', 'ro'],
    ['Mândrie', 'Aroganță', 'Emotions', 'ro'],
    ['Rușine', 'Vinovăție', 'Emotions', 'ro'],
    ['Regret', 'Remușcare', 'Emotions', 'ro'],
    ['Recunoștință', 'Apreciere', 'Emotions', 'ro'],
    ['Admirație', 'Venerare', 'Emotions', 'ro'],
    ['Compasiune', 'Empatie', 'Emotions', 'ro'],
    ['Solidaritate', 'Sprijin', 'Emotions', 'ro'],
    ['Speranță', 'Optimism', 'Emotions', 'ro'],
    ['Dezamăgire', 'Deznădejde', 'Emotions', 'ro'],
    ['Plictiseală', 'Monotonie', 'Emotions', 'ro'],
    ['Entuziasm', 'Energie', 'Emotions', 'ro'],
    ['Plăcere', 'Satisfacție', 'Emotions', 'ro'],
    ['Confort', 'Siguranță', 'Emotions', 'ro'],
    ['Relaxare', 'Liniște', 'Emotions', 'ro'],
    ['Pace', 'Echilibru', 'Emotions', 'ro'],
    ['Stres', 'Presiune', 'Emotions', 'ro'],
    ['Oboseală', 'Epuizare', 'Emotions', 'ro'],
    ['Confuzie', 'Dezorientare', 'Emotions', 'ro'],
    ['Curiozitate', 'Interes', 'Emotions', 'ro'],
    ['Indiferență', 'Apatie', 'Emotions', 'ro'],
    ['Respingere', 'Aversiune', 'Emotions', 'ro'],
    ['Ușurare', 'Relaxare', 'Emotions', 'ro'],
    ['Nostalgie', 'Dor', 'Emotions', 'ro'],
    ['Euphorie', 'Extaz', 'Emotions', 'ro'],
    ['Scepticism', 'Îndoială', 'Emotions', 'ro'],
    ['Încredere', 'Asigurare', 'Emotions', 'ro'],
    ['Vulnerabilitate', 'Sensibilitate', 'Emotions', 'ro'],
    ['Căldură', 'Afecțiune', 'Emotions', 'ro'],
    ['Rece', 'Detașare', 'Emotions', 'ro'],

    // ============================================
    // MYTHOLOGY (Mitologie) - 40 pairs
    // ============================================
    ['Zeus', 'Poseidon', 'Mythology', 'ro'],
    ['Hades', 'Ares', 'Mythology', 'ro'],
    ['Apollo', 'Hermes', 'Mythology', 'ro'],
    ['Hera', 'Demetra', 'Mythology', 'ro'],
    ['Atena', 'Artemis', 'Mythology', 'ro'],
    ['Afrodita', 'Hestia', 'Mythology', 'ro'],
    ['Persefona', 'Euridice', 'Mythology', 'ro'],
    ['Hercule', 'Perseu', 'Mythology', 'ro'],
    ['Ahile', 'Odiseu', 'Mythology', 'ro'],
    ['Icar', 'Dedal', 'Mythology', 'ro'],
    ['Mid', 'Narcis', 'Mythology', 'ro'],
    ['Meduza', 'Ciclop', 'Mythology', 'ro'],
    ['Minotaur', 'Centaur', 'Mythology', 'ro'],
    ['Hidra', 'Chimera', 'Mythology', 'ro'],
    ['Sirenă', 'Harpiă', 'Mythology', 'ro'],
    ['Gorgonă', 'Sfinx', 'Mythology', 'ro'],
    ['Feniks', 'Dragon', 'Mythology', 'ro'],
    ['Pegas', 'Unicorn', 'Mythology', 'ro'],
    ['Grifon', 'Basilisc', 'Mythology', 'ro'],
    ['Titan', 'Gigant', 'Mythology', 'ro'],
    ['Odin', 'Thor', 'Mythology', 'ro'],
    ['Loki', 'Fenrir', 'Mythology', 'ro'],
    ['Freya', 'Frigg', 'Mythology', 'ro'],
    ['Zeus', 'Jupiter', 'Mythology', 'ro'],
    ['Osiris', 'Anubis', 'Mythology', 'ro'],
    ['Ra', 'Amon', 'Mythology', 'ro'],
    ['Isis', 'Hathor', 'Mythology', 'ro'],
    ['Sfântul Gheorghe', 'Sfântul Mihai', 'Mythology', 'ro'],
    ['Zburător', 'Solomonar', 'Mythology', 'ro'],
    ['Iele', 'Zâne', 'Mythology', 'ro'],
    ['Strigoi', 'Moroi', 'Mythology', 'ro'],
    ['Vârcolac', 'Vampir', 'Mythology', 'ro'],
    ['Zmeu', 'Balaur', 'Mythology', 'ro'],
    ['Apa vie', 'Apa moartă', 'Mythology', 'ro'],
    ['Cornul abundenței', 'Toiagul lui Asclepius', 'Mythology', 'ro'],
    ['Scutul lui Ahile', 'Coiful lui Hercule', 'Mythology', 'ro'],
    ['Sulița lui Zeus', 'Tridentul lui Poseidon', 'Mythology', 'ro'],
    ['Arcul lui Apollo', 'Arcul lui Artemis', 'Mythology', 'ro'],
    ['Pocalul lui Hristos', 'Sulița destinului', 'Mythology', 'ro'],
    ['Potir', 'Cornul lui Amaltheea', 'Mythology', 'ro'],

    // ============================================
    // GEOGRAPHY (Geografie) - 40 pairs
    // ============================================
    ['Europa', 'Asia', 'Geography', 'ro'],
    ['Africa', 'Australia', 'Geography', 'ro'],
    ['America de Nord', 'America de Sud', 'Geography', 'ro'],
    ['Antarctica', 'Oceania', 'Geography', 'ro'],
    ['Oceanul Atlantic', 'Oceanul Pacific', 'Geography', 'ro'],
    ['Oceanul Indian', 'Oceanul Arctic', 'Geography', 'ro'],
    ['Marea Mediterană', 'Marea Neagră', 'Geography', 'ro'],
    ['Marea Nordului', 'Marea Baltică', 'Geography', 'ro'],
    ['Himalaya', 'Alpi', 'Geography', 'ro'],
    ['Munții Carpați', 'Munții Balcani', 'Geography', 'ro'],
    ['Everest', 'K2', 'Geography', 'ro'],
    ['Kilimanjaro', 'Mont Blanc', 'Geography', 'ro'],
    ['Sahara', 'Gobi', 'Geography', 'ro'],
    ['Kalahari', 'Deșertul Atacama', 'Geography', 'ro'],
    ['Nil', 'Amazon', 'Geography', 'ro'],
    ['Dunărea', 'Volga', 'Geography', 'ro'],
    ['Mississippi', 'Yangtze', 'Geography', 'ro'],
    ['Lacul Baikal', 'Lacul Victoria', 'Geography', 'ro'],
    ['Marea Moartă', 'Marea Caspică', 'Geography', 'ro'],
    ['Marea Roșie', 'Marea Galbenă', 'Geography', 'ro'],
    ['Paris', 'Londra', 'Geography', 'ro'],
    ['Roma', 'Atena', 'Geography', 'ro'],
    ['Berlin', 'Viena', 'Geography', 'ro'],
    ['Madrid', 'Lisabona', 'Geography', 'ro'],
    ['New York', 'Los Angeles', 'Geography', 'ro'],
    ['Tokyo', 'Seul', 'Geography', 'ro'],
    ['Sydney', 'Melbourne', 'Geography', 'ro'],
    ['Cairo', 'Casablanca', 'Geography', 'ro'],
    ['Rio de Janeiro', 'Buenos Aires', 'Geography', 'ro'],
    ['București', 'Budapesta', 'Geography', 'ro'],
    ['Moscova', 'Sankt Petersburg', 'Geography', 'ro'],
    ['Beijing', 'Shanghai', 'Geography', 'ro'],
    ['Delhi', 'Mumbai', 'Geography', 'ro'],
    ['Bangkok', 'Singapore', 'Geography', 'ro'],
    ['Dubai', 'Doha', 'Geography', 'ro'],
    ['Istanbul', 'Ankara', 'Geography', 'ro'],
    ['Cape Town', 'Johannesburg', 'Geography', 'ro'],
    ['Toronto', 'Vancouver', 'Geography', 'ro'],
    ['Mexic', 'Buenos Aires', 'Geography', 'ro'],
    ['Veneția', 'Amsterdam', 'Geography', 'ro'],

    // ============================================
    // HOBBIES (Hobby-uri) - 40 pairs
    // ============================================
    ['Pescuit', 'Vânătoare', 'Hobbies', 'ro'],
    ['Grădinărit', 'Floricultură', 'Hobbies', 'ro'],
    ['Fotografie', 'Filmare', 'Hobbies', 'ro'],
    ['Pictură', 'Desen', 'Hobbies', 'ro'],
    ['Sculptură', 'Modelaj', 'Hobbies', 'ro'],
    ['Cusut', 'Tricotat', 'Hobbies', 'ro'],
    ['Brodat', 'Quilt', 'Hobbies', 'ro'],
    ['Origami', 'Quilling', 'Hobbies', 'ro'],
    ['Șah', 'Dame', 'Hobbies', 'ro'],
    ['Sudoku', 'Cuvinte încrucișate', 'Hobbies', 'ro'],
    ['Puzzle', 'Cub Rubik', 'Hobbies', 'ro'],
    ['Board games', 'Cărți de joc', 'Hobbies', 'ro'],
    ['Roleplay', 'Jocuri de strategie', 'Hobbies', 'ro'],
    ['Lectură', 'Scriere', 'Hobbies', 'ro'],
    ['Poezie', 'Proză', 'Hobbies', 'ro'],
    ['Blogging', 'Vlogging', 'Hobbies', 'ro'],
    ['Podcasting', 'Streaming', 'Hobbies', 'ro'],
    ['Gaming', 'Esports', 'Hobbies', 'ro'],
    ['Colecționare timbre', 'Colecționare monede', 'Hobbies', 'ro'],
    ['Filatelie', 'Numismatică', 'Hobbies', 'ro'],
    ['Antichități', 'Vintage', 'Hobbies', 'ro'],
    ['Restaurare', 'Renovare', 'Hobbies', 'ro'],
    ['DIY', 'Handmade', 'Hobbies', 'ro'],
    ['Croitorie', 'Design vestimentar', 'Hobbies', 'ro'],
    ['Cântat', 'Compoziție', 'Hobbies', 'ro'],
    ['Chitară', 'Pian', 'Hobbies', 'ro'],
    ['Dans', 'Balet', 'Hobbies', 'ro'],
    ['Yoga', 'Pilates', 'Hobbies', 'ro'],
    ['Alergare', 'Maraton', 'Hobbies', 'ro'],
    ['Ciclism', 'MTB', 'Hobbies', 'ro'],
    ['Înot', 'Scufundări', 'Hobbies', 'ro'],
    ['Schi', 'Snowboard', 'Hobbies', 'ro'],
    ['Escaladă', 'Alpinism', 'Hobbies', 'ro'],
    ['Camping', 'Drumeție', 'Hobbies', 'ro'],
    ['Survival', 'Bushcraft', 'Hobbies', 'ro'],
    ['Astronomie', 'Astrofotografie', 'Hobbies', 'ro'],
    ['Genealogie', 'Istorie locală', 'Hobbies', 'ro'],
    ['Călătorii', 'Backpacking', 'Hobbies', 'ro'],
    ['Gătit', 'Cofetărie', 'Hobbies', 'ro'],
    ['Degustare vin', 'Degustare cafea', 'Hobbies', 'ro'],

    // ============================================
    // LITERATURE (Literatură) - 40 pairs
    // ============================================
    ['Roman', 'Nuvelă', 'Literature', 'ro'],
    ['Povestire', 'Schiță', 'Literature', 'ro'],
    ['Poezie', 'Elegie', 'Literature', 'ro'],
    ['Odă', 'Sonet', 'Literature', 'ro'],
    ['Fabula', 'Parabolă', 'Literature', 'ro'],
    ['Epopee', 'Baladă', 'Literature', 'ro'],
    ['Teatru', 'Dramă', 'Literature', 'ro'],
    ['Comedie', 'Tragedie', 'Literature', 'ro'],
    ['Satiră', 'Pamphlet', 'Literature', 'ro'],
    ['Autobiografie', 'Memorialistică', 'Literature', 'ro'],
    ['Biografie', 'Portret', 'Literature', 'ro'],
    ['Jurnal', 'Corespondență', 'Literature', 'ro'],
    ['Eseu', 'Articol', 'Literature', 'ro'],
    ['Critică', 'Istorie literară', 'Literature', 'ro'],
    ['Poveste', 'Basme', 'Literature', 'ro'],
    ['Legenda', 'Mit', 'Literature', 'ro'],
    ['Saga', 'Cronica', 'Literature', 'ro'],
    ['Trilogie', 'Serie', 'Literature', 'ro'],
    ['Antologie', 'Culegere', 'Literature', 'ro'],
    ['Prefață', 'Postfață', 'Literature', 'ro'],
    ['Prolog', 'Epilog', 'Literature', 'ro'],
    ['Capitol', 'Volum', 'Literature', 'ro'],
    ['Personaj', 'Protagonist', 'Literature', 'ro'],
    ['Antagonist', 'Figură secundară', 'Literature', 'ro'],
    ['Narat', 'Descriere', 'Literature', 'ro'],
    ['Dialog', 'Monolog', 'Literature', 'ro'],
    ['Conflict', 'Intriga', 'Literature', 'ro'],
    ['Climax', 'Denouement', 'Literature', 'ro'],
    ['Simbolism', 'Alegorie', 'Literature', 'ro'],
    ['Metaforă', 'Comparație', 'Literature', 'ro'],
    ['Ironie', 'Sarcasm', 'Literature', 'ro'],
    ['Hiperbolă', 'Eufemism', 'Literature', 'ro'],
    ['Aliterație', 'Asonanță', 'Literature', 'ro'],
    ['Rimă', 'Ritm', 'Literature', 'ro'],
    ['Strofă', 'Vers', 'Literature', 'ro'],
    ['Editură', 'Tipografie', 'Literature', 'ro'],
    ['Bibliotecă', 'Librărie', 'Literature', 'ro'],
    ['Manuscris', 'Ediție', 'Literature', 'ro'],
    ['Bestseller', 'Carte de buzunar', 'Literature', 'ro'],
    ['Audiobook', 'E-book', 'Literature', 'ro'],

    // ============================================
    // MOVIES (Filme) - 40 pairs
    // ============================================
    ['Action', 'Aventură', 'Movies', 'ro'],
    ['Thriller', 'Horror', 'Movies', 'ro'],
    ['Comedie', 'Parodie', 'Movies', 'ro'],
    ['Romantic', 'Melodramă', 'Movies', 'ro'],
    ['Drama', 'Tragedie', 'Movies', 'ro'],
    ['Science fiction', 'Fantasy', 'Movies', 'ro'],
    ['Western', 'Gangster', 'Movies', 'ro'],
    ['Război', 'Istoric', 'Movies', 'ro'],
    ['Documentar', 'Mockumentar', 'Movies', 'ro'],
    ['Animație', 'Stop-motion', 'Movies', 'ro'],
    ['Musical', 'Operă', 'Movies', 'ro'],
    ['Noir', 'Neo-noir', 'Movies', 'ro'],
    ['Indie', 'Art house', 'Movies', 'ro'],
    ['Blockbuster', 'Film de autor', 'Movies', 'ro'],
    ['Prequel', 'Sequel', 'Movies', 'ro'],
    ['Reboot', 'Remake', 'Movies', 'ro'],
    ['Spin-off', 'Crossover', 'Movies', 'ro'],
    ['Scenariu', 'Scenariu adaptat', 'Movies', 'ro'],
    ['Regizor', 'Producător', 'Movies', 'ro'],
    ['Actor', 'Star', 'Movies', 'ro'],
    ['Cameraman', 'Monteur', 'Movies', 'ro'],
    ['Scenograf', 'Costumier', 'Movies', 'ro'],
    ['Sunetist', 'Compozitor', 'Movies', 'ro'],
    ['Efecte speciale', 'Efecte vizuale', 'Movies', 'ro'],
    ['CGI', 'Motion capture', 'Movies', 'ro'],
    ['Premiera', 'Gala', 'Movies', 'ro'],
    ['Festival', 'Premii', 'Movies', 'ro'],
    ['Oscar', 'Globul de Aur', 'Movies', 'ro'],
    ['Palme d\'Or', 'Ursul de Aur', 'Movies', 'ro'],
    ['Cannes', 'Veneția', 'Movies', 'ro'],
    ['Cinematograf', 'Multiplex', 'Movies', 'ro'],
    ['IMAX', '3D', 'Movies', 'ro'],
    ['4K', 'HDR', 'Movies', 'ro'],
    ['Streaming', 'Video on demand', 'Movies', 'ro'],
    ['Netflix', 'HBO', 'Movies', 'ro'],
    ['Disney', 'Pixar', 'Movies', 'ro'],
    ['Marvel', 'DC', 'Movies', 'ro'],
    ['Bollywood', 'Hollywood', 'Movies', 'ro'],
    ['Clasic', 'Cult', 'Movies', 'ro'],
    ['Film mut', 'Film sonor', 'Movies', 'ro'],

    // ============================================
    // TECHNOLOGY (Tehnologie) - 40 pairs
    // ============================================
    ['Computer', 'Laptop', 'Technology', 'ro'],
    ['Tabletă', 'Telefon', 'Technology', 'ro'],
    ['Smartphone', 'Feature phone', 'Technology', 'ro'],
    ['Aplicație', 'Software', 'Technology', 'ro'],
    ['Hardware', 'Firmware', 'Technology', 'ro'],
    ['Procesor', 'Placă video', 'Technology', 'ro'],
    ['RAM', 'Stocare', 'Technology', 'ro'],
    ['SSD', 'HDD', 'Technology', 'ro'],
    ['Cloud', 'Server', 'Technology', 'ro'],
    ['Rețea', 'Internet', 'Technology', 'ro'],
    ['WiFi', 'Bluetooth', 'Technology', 'ro'],
    ['5G', '4G', 'Technology', 'ro'],
    ['Router', 'Switch', 'Technology', 'ro'],
    ['Firewall', 'Antivirus', 'Technology', 'ro'],
    ['VPN', 'Proxy', 'Technology', 'ro'],
    ['Cryptomonedă', 'Blockchain', 'Technology', 'ro'],
    ['Bitcoin', 'Ethereum', 'Technology', 'ro'],
    ['NFT', 'Token', 'Technology', 'ro'],
    ['AI', 'Machine learning', 'Technology', 'ro'],
    ['Deep learning', 'Neural network', 'Technology', 'ro'],
    ['Chatbot', 'Asistent virtual', 'Technology', 'ro'],
    ['Robot', 'Dronă', 'Technology', 'ro'],
    ['Automatizare', 'RPA', 'Technology', 'ro'],
    ['IoT', 'Smart home', 'Technology', 'ro'],
    ['Wearable', 'Smartwatch', 'Technology', 'ro'],
    ['VR', 'AR', 'Technology', 'ro'],
    ['Headset', 'Controller', 'Technology', 'ro'],
    ['Imprimantă 3D', 'Scaner 3D', 'Technology', 'ro'],
    ['Laser', 'LED', 'Technology', 'ro'],
    ['OLED', 'QLED', 'Technology', 'ro'],
    ['Baterie', 'Celulă solară', 'Technology', 'ro'],
    ['Wireless charging', 'Fast charging', 'Technology', 'ro'],
    ['USB-C', 'Thunderbolt', 'Technology', 'ro'],
    ['HDMI', 'DisplayPort', 'Technology', 'ro'],
    ['GPS', 'GLONASS', 'Technology', 'ro'],
    ['Senzor', 'Actuator', 'Technology', 'ro'],
    ['Compilator', 'Interpretor', 'Technology', 'ro'],
    ['API', 'SDK', 'Technology', 'ro'],
    ['Bug', 'Eroare', 'Technology', 'ro'],
    ['Patch', 'Update', 'Technology', 'ro'],

    // ============================================
    // SPACE (Spațiu) - 40 pairs
    // ============================================
    ['Soare', 'Steaua', 'Space', 'ro'],
    ['Planetă', 'Gigant gazos', 'Space', 'ro'],
    ['Steauă neutronică', 'Gaură neagră', 'Space', 'ro'],
    ['Supernova', 'Nebuloasă', 'Space', 'ro'],
    ['Galaxie', 'Calea Lactee', 'Space', 'ro'],
    ['Cuantum', 'Materie întunecată', 'Space', 'ro'],
    ['Pulsare', 'Quasar', 'Space', 'ro'],
    ['Meteorit', 'Asteroid', 'Space', 'ro'],
    ['Cometă', 'Centaur', 'Space', 'ro'],
    ['Satelit', 'Stație spațială', 'Space', 'ro'],
    ['Lună', 'Phobos', 'Space', 'ro'],
    ['Telescop', 'Observator', 'Space', 'ro'],
    ['Rachetă', 'Navetă', 'Space', 'ro'],
    ['Capsulă', 'Modul lunar', 'Space', 'ro'],
    ['Satelit artificial', 'Sondă spațială', 'Space', 'ro'],
    ['Rover', 'Lander', 'Space', 'ro'],
    ['Stație orbitală', 'Bază lunară', 'Space', 'ro'],
    ['Terraformare', 'Colonizare', 'Space', 'ro'],
    ['Astronaut', 'Cosmonaut', 'Space', 'ro'],
    ['Zero gravity', 'Microgravity', 'Space', 'ro'],
    ['Orbită', 'Traiectorie', 'Space', 'ro'],
    ['Eclipsă solară', 'Eclipsă lunară', 'Space', 'ro'],
    ['Transit', 'Ocultare', 'Space', 'ro'],
    ['Constelație', 'Zodiac', 'Space', 'ro'],
    ['Orion', 'Cassiopeia', 'Space', 'ro'],
    ['Ursa Mare', 'Ursa Mică', 'Space', 'ro'],
    ['Polaris', 'Sirius', 'Space', 'ro'],
    ['Vega', 'Altair', 'Space', 'ro'],
    ['Mart', 'Venus', 'Space', 'ro'],
    ['Jupiter', 'Saturn', 'Space', 'ro'],
    ['Uranus', 'Neptun', 'Space', 'ro'],
    ['Mercur', 'Pluto', 'Space', 'ro'],
    ['Centura de asteroizi', 'Norul Oort', 'Space', 'ro'],
    ['Big Bang', 'Inflație cosmică', 'Space', 'ro'],
    ['Radiație cosmică', 'Vânt solar', 'Space', 'ro'],
    ['Aurora', 'Curent Van Allen', 'Space', 'ro'],
    ['Trou Noir', 'Trou de ver', 'Space', 'ro'],
    ['Multivers', 'Parallel universe', 'Space', 'ro'],
    ['Singularitate', 'Event horizon', 'Space', 'ro'],
    ['Exoplanetă', 'Super-Pământ', 'Space', 'ro'],
];
